default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: root
  password: root

development:
  <<: *default
  database: mtomady
  host: localhost
  port: 5432

test:
  <<: *default
  database: mtomady
  host: database
  port: 5432

production:
  <<: *default
  database: mtomady
  username: <%= ENV['MYAPP_DATABASE_USERNAME'] %>
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
